### PR TITLE
adding projects

### PR DESCRIPTION
**Pull request by Bikaskumar572**
added 2 project which can help .....
can add more if u want......
chat app heroku link : https://bikas-chat-application.herokuapp.com/
github link : https://github.com/Bikaskumar572

### CODE REVIEW

**Comment by jaskiratmokha** [comment]
@Bikaskumar572 These projects would be extremely helpful for the community, thanks for showing interest for the cause. It would really great if you can create a new folder Named as "Projects/Web projects" and add these projects there as it will be more structured that way. Again, I would like to thank you for helping the community. Looking forward for your next move.

**Comment by Bikaskumar572** [comment]
@jaskiratmokha , done added 3 projects in web projects folder

**Comment by Bikaskumar572** [comment]
all the projects are uploaded on heroku if u want u can it in my profile.
github link :  https://github.com/Bikaskumar572

**Comment by Bikaskumar572** [comment]
@jaskiratmokha

**Comment by jaskiratmokha** [comment]
Thanks a lot @Bikaskumar572 for the contribution.

**Pull request merged**
